### ISSUE TITLE
Content missing issue on homepage

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Joy--Internal-13th-june#1]
Bug - Some content missing and misplaced on homepage.
Exp - Content on homepage should be same on preview as showing on live.
Ref Link - https://drive.google.com/file/d/150zc0quMUNpLrMnA3Bc9sV885kIBzRxz/view

**Comment by devShivDuttChauhan** [comment]
I have fixed this issues.

**Comment by ankitcedcoss** [comment]
Bug Fixed
